--- 
RID: varchar # Participant roster ID
VISCODE: varchar # Visit code
EXAMDATE: date # Examination date
REPEATCODE: varchar # Repeat code
Month_bl: float # Months from baseline based on EXAMDATES
AGE: float # Age at baseline
SEX: varchar # Sex
EDUCATION: int # Education
ETHNICITY: varchar # Ethnicity -hispanic, not hispanic unknown
RACE: varchar # Race - white, black, asian, Am Indian/Alaskan, hawaiian/other PI, more than one, unknown white
MARRY: varchar # Marital status at basline, married, never married, unkown, widowed, divorced
CDRSB: float # CDR-SB, clinical dementia rating sum of boxes
ADAS11: float # ADAS11, alzheimer's disease assesment scale
ADAS13: float # ADAS13, alzheimer's disease assesment scale
MMSE: int # Mini mental state exam
RAVLT_immediate: int # RAVLT Immediate (sum of 5 trials)
RAVLT_learning: int # RAVLT Learning (trial 5 - trial 1)
RAVLT_forgetting: int # RAVLT Forgetting (trial 5 - delayed)
RAVLT_perc_forgetting: float # RAVLT Percent Forgetting 
FAQ: int # Functional assessment questionnaire
MOCA: int # Montreal cognitive assessment
LDELTOTAL: int # Logical Memory - Delayed Recall <br />Total Number of Story Units Recalled
APGEN1: int # Genotype - Allele 1
APGEN2: int # Genotype - Allele 2
ABETA_MEDIAN: float # Amyloid beta
TAU_MEDIAN: float # Tau protein
TAU_MEDIAN_ABETA_MEDIAN: float # Tau protein
PTAU_MEDIAN: float # phosphorylated Tau
PTAU_MEDIAN_ABETA_MEDIAN: float # phosphorylated Tau
AB42: float # Abeta1-42 result in plasma
AB40: float # Abeta1-40 result in plasma
APOE2: boolean # APOE2 gene variant
APOE3: boolean # APOE3 gene variant
APOE4: boolean # APOE4 gene variant
RESTfMRI: boolean # Resting state fMRI
FDG: boolean # Average FDG-PET of angular, temporal, and posterior cingulate
PIB: boolean # Average PIB SUVR of frontal cortex, anterior cingulate, precuneus cortex, and parietal cortex
AV45: boolean # Average AV45 SUVR of frontal, anterior cingulate, precuneus, and parietal cortex relative to the cerebellum
DTI: boolean # Diffusion tesnor imaging MRI
ASL: boolean # Arterial spin labeling 
DX: varchar # Diagnosis status
DX_STRATIFICATION: varchar #diagnosis stratification