--- 
RID: varchar
VISCODE: varchar
REPEATCODE: varchar
DATE: date
AGE: varchar
Month_bl: varchar
PTGENDER: varchar
PTRACE: varchar
FLDSTRENG: varchar
AUX_DIAGNOSIS: varchar
AUX_STRATIFICATION: varchar
TIME_1: time
MRI_Measure1: float
TIME_2: time
MRI_Measure2: float
TIME_3: time
MRI_Measure3: float
TIME_4: time
MRI_Measure4: float
TIME_5: time
MRI_Measure5: float
TIME_6: time
MRI_Measure6: float
