--- 
RID: varchar
VISCODE: varchar
REPEATCODE: varchar
DATE: date
AGE: varchar
Month_bl: varchar
PTGENDER: varchar
PTRACE: varchar
FLDSTRENG: varchar
AUX_DIAGNOSIS: varchar
AUX_STRATIFICATION: varchar
TIME_1: time
Measure1: float
TIME_2: time
Measure2: float
TIME_3: time
Measure3: float
TIME_4: time
Measure4: float
TIME_5: time
Measure5: float
TIME_6: time
Measure6: float
